---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
library(lubridate)
```

```{r}
conflict = 
  read_csv("../pols559_final_data/conflict.csv")
```

```{r}
conflict %>% 
  filter(date>"2001-01-05" & date<"2020-09-04") %>% 
  mutate(date2 = ceiling_date(date, unit = "week", week_start = 5), 
         wday = wday(date2, label = T)) %>%
  group_by(date = date2) %>%
  summarise(turkish = sum(turkish), 
            kurdish = sum(kurdish)) %>% 
  write_csv("preprocessing/conflict_grouped.csv")
```
```{r}
unique(conflict$date2) %>% length()
```



```{r}
sermons %>% summary()
```





```{r}
conflict %>% 
  filter(wday(date) == 6) %>% 
  write_csv("preprocessing/rates_grouped.csv")
```


```{r}
sermons = 
  sermons %>% 
  mutate(id = 1:nrow(sermons), .before=date)
```
```{r}
head(sermons)
```




```{r}
test = 
  fuzzy_left_join(
  sermons, conflict,
  by = c(
    "date" = "start",
    "date" = "end"
    ),
  match_fun = list(`>=`, `<=`)
  ) 
```


```{r}
final = test %>% 
  group_by(id, date,location, translated) %>%
  summarize(casualty = sum(casualty.y)) %>%
  mutate(casualty = ifelse(is.na(casualty), 0, casualty)) 
```

```{r}
casualty = 0
for (i in 1:nrow(sermons)){
  casualty = 0
  for (j in 1:nrow(conflict)){
    casualty = casualty + conflict$casualty[j]
    if(sermons$date[i] %within% conflict$date_int[j]){
      sermons$casualty[i] = casualty
      print(paste(sermons$date[i], casualty, sep = "="))
    }
  else{
    sermons$casualty[i] = 0
    }
  }
}
```

```{r}
sermons %>% 
  mutate(casualty = ifelse(date %within% conflict$date_int, 1, 0))
```


```{r}
conflict %>% 
  group_by(lubridate::month(date)) %>%
  summarize(total = sum(casualty))
```


```{r}
sermons %>% 
  filter(is.na(price)) %>%
  distinct(date) %>%
  select(date) %>%
  kable() %>%
  kable_paper()
```



```{r}
sermons %>% 
  group_by(lubridate::year(date)) %>%
  count()
```




```{r}
setwd(tempdir())
stmBrowser(stm30, data=meta, c("casualty", "price", "ramadan"),
                   text="translated")
```

```{r}
#Remove files
unlink("stm-visualization", recursive=TRUE)
```